//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GovernmentParse.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GovernmentParse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архів комітетів існує починаючи с VI скликання.
        /// </summary>
        public static string ArchiveOfCommitteeDoesNotExist {
            get {
                return ResourceManager.GetString("ArchiveOfCommitteeDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Архів фракцій існує починаючи с VI скликання.
        /// </summary>
        public static string ArchiveOfFractionsDoesNotExist {
            get {
                return ResourceManager.GetString("ArchiveOfFractionsDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Brief_512 {
            get {
                object obj = ResourceManager.GetObject("Brief_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Brief_white_100px {
            get {
                object obj = ResourceManager.GetObject("Brief_white_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Businessman_white_104px {
            get {
                object obj = ResourceManager.GetObject("Businessman_white_104px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap calendar {
            get {
                object obj = ResourceManager.GetObject("calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calendar_25px {
            get {
                object obj = ResourceManager.GetObject("Calendar_25px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap calendar_7_white_512 {
            get {
                object obj = ResourceManager.GetObject("calendar_7_white_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calendar_7_white_96px {
            get {
                object obj = ResourceManager.GetObject("Calendar_7_white_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calendar_white_100px {
            get {
                object obj = ResourceManager.GetObject("Calendar_white_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Cancel_48px {
            get {
                object obj = ResourceManager.GetObject("Cancel_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдається зберегти інформацію про помилку.
        /// </summary>
        public static string CantSaveError {
            get {
                return ResourceManager.GetString("CantSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Circled_Play_48px {
            get {
                object obj = ResourceManager.GetObject("Circled_Play_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робота з комітетами.
        /// </summary>
        public static string CommitteeHeader {
            get {
                return ResourceManager.GetString("CommitteeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження інформації про комітети.
        /// </summary>
        public static string CommitteesSaved {
            get {
                return ResourceManager.GetString("CommitteesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження інформації про роботу комітетів.
        /// </summary>
        public static string CommitteesWorkSaved {
            get {
                return ResourceManager.GetString("CommitteesWorkSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при порівнянні завантажених файлів.
        /// </summary>
        public static string CompareDownloadedError {
            get {
                return ResourceManager.GetString("CompareDownloadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при порівнянні знайдених данних зі збереженими.
        /// </summary>
        public static string CompareError {
            get {
                return ResourceManager.GetString("CompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задайте меньший проміжок часу. Кількість знайдених записів перевищує 100 та дорівнює .
        /// </summary>
        public static string CountWarning {
            get {
                return ResourceManager.GetString("CountWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при створенні зведеної таблиці законопроектів.
        /// </summary>
        public static string CreateLawsTableError {
            get {
                return ResourceManager.GetString("CreateLawsTableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Date_span_white_512 {
            get {
                object obj = ResourceManager.GetObject("Date_span_white_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Date_Span_white_96px {
            get {
                object obj = ResourceManager.GetObject("Date_Span_white_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Початкова дата не може бути більшою ніж кінцева.
        /// </summary>
        public static string DatePickerWarning {
            get {
                return ResourceManager.GetString("DatePickerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робота з депутатами.
        /// </summary>
        public static string DeputiesHeader {
            get {
                return ResourceManager.GetString("DeputiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження інформації про законотворчу активність депутатів.
        /// </summary>
        public static string DeputyLawActivitySaved {
            get {
                return ResourceManager.GetString("DeputyLawActivitySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження інформації про запити депутатів.
        /// </summary>
        public static string DeputyQueriesSaved {
            get {
                return ResourceManager.GetString("DeputyQueriesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження загальної інформації про депутатів.
        /// </summary>
        public static string DeputySaved {
            get {
                return ResourceManager.GetString("DeputySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження інформації про виступи депутатів.
        /// </summary>
        public static string DeputySpeechesSaved {
            get {
                return ResourceManager.GetString("DeputySpeechesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження інформації про голосування депутатів.
        /// </summary>
        public static string DeputyVotingSaved {
            get {
                return ResourceManager.GetString("DeputyVotingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при завантаженні файлів, необхідних для порівняння.
        /// </summary>
        public static string DownloadForCompareError {
            get {
                return ResourceManager.GetString("DownloadForCompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робота з фракціями.
        /// </summary>
        public static string FractionsHeader {
            get {
                return ResourceManager.GetString("FractionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження інформації про фракції.
        /// </summary>
        public static string FractionsSaved {
            get {
                return ResourceManager.GetString("FractionsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap group_512 {
            get {
                object obj = ResourceManager.GetObject("group_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap High_Priority_48px {
            get {
                object obj = ResourceManager.GetObject("High_Priority_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введить номер закону.
        /// </summary>
        public static string InvalidSearchLowTextBoxValue {
            get {
                return ResourceManager.GetString("InvalidSearchLowTextBoxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робота з законопроектами.
        /// </summary>
        public static string LawsHeader {
            get {
                return ResourceManager.GetString("LawsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logo_2014 {
            get {
                object obj = ResourceManager.GetObject("logo_2014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження законопроектів і прилеглих документів.
        /// </summary>
        public static string LowsAndFilesSaved {
            get {
                return ResourceManager.GetString("LowsAndFilesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap man {
            get {
                object obj = ResourceManager.GetObject("man", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва нового комітета:.
        /// </summary>
        public static string NewCommiteeName {
            get {
                return ResourceManager.GetString("NewCommiteeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Им&apos;я депутата, інформацію про якого було збережено:.
        /// </summary>
        public static string NewDeputy {
            get {
                return ResourceManager.GetString("NewDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Им&apos;я депутата, фото якого було збережено:.
        /// </summary>
        public static string NewDeputyPhoto {
            get {
                return ResourceManager.GetString("NewDeputyPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва нового супровідного документа:.
        /// </summary>
        public static string NewDocumentName {
            get {
                return ResourceManager.GetString("NewDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва нової фракції:.
        /// </summary>
        public static string NewFraction {
            get {
                return ResourceManager.GetString("NewFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер нового законопроекта:.
        /// </summary>
        public static string NewLawNumber {
            get {
                return ResourceManager.GetString("NewLawNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap News1111_100px {
            get {
                object obj = ResourceManager.GetObject("News1111_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тиждень нового засідання:.
        /// </summary>
        public static string NewSessionPlan {
            get {
                return ResourceManager.GetString("NewSessionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий rtf документ поіменного голосування:.
        /// </summary>
        public static string NewVotingRtfDoc {
            get {
                return ResourceManager.GetString("NewVotingRtfDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий xml документ поіменного голосування:.
        /// </summary>
        public static string NewVotingXmlDoc {
            get {
                return ResourceManager.GetString("NewVotingXmlDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нових чи оновлених документів немає.
        /// </summary>
        public static string NothingToSave {
            get {
                return ResourceManager.GetString("NothingToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ok_48px {
            get {
                object obj = ResourceManager.GetObject("Ok_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при пошуку інформації.
        /// </summary>
        public static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження інформації про розклад пленарних засідань.
        /// </summary>
        public static string PlenarySessionSaved {
            get {
                return ResourceManager.GetString("PlenarySessionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робота зі звітом.
        /// </summary>
        public static string ReportHeader {
            get {
                return ResourceManager.GetString("ReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попередження.
        /// </summary>
        public static string RetentionHeader {
            get {
                return ResourceManager.GetString("RetentionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  вже відбулося, Ви впевнені, що бажаєте знову шукати нові дані?.
        /// </summary>
        public static string RetentionMessage {
            get {
                return ResourceManager.GetString("RetentionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Roboto_Regular {
            get {
                object obj = ResourceManager.GetObject("Roboto_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save_48px {
            get {
                object obj = ResourceManager.GetObject("Save_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save_icon_black_48px {
            get {
                object obj = ResourceManager.GetObject("Save_icon_black_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка при збереженні інформації.
        /// </summary>
        public static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Schedule_white_96px {
            get {
                object obj = ResourceManager.GetObject("Schedule_white_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошук був припинений.
        /// </summary>
        public static string SearchStopped {
            get {
                return ResourceManager.GetString("SearchStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Робота з пленарними засіданнями.
        /// </summary>
        public static string SessionsHeader {
            get {
                return ResourceManager.GetString("SessionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sign_up_whit_e_512 {
            get {
                object obj = ResourceManager.GetObject("sign_up_whit_e_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sign_Up_white_96px {
            get {
                object obj = ResourceManager.GetObject("Sign_Up_white_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Після збереження тут з&apos;явиться звіт.
        /// </summary>
        public static string StartNotification {
            get {
                return ResourceManager.GetString("StartNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Збереження завершено!.
        /// </summary>
        public static string SuccessSave {
            get {
                return ResourceManager.GetString("SuccessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap timeschedule_512 {
            get {
                object obj = ResourceManager.GetObject("timeschedule_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap training {
            get {
                object obj = ResourceManager.GetObject("training", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Training_25px {
            get {
                object obj = ResourceManager.GetObject("Training_25px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Training_white_100px {
            get {
                object obj = ResourceManager.GetObject("Training_white_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Training_white_100px1 {
            get {
                object obj = ResourceManager.GetObject("Training_white_100px1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap treangle {
            get {
                object obj = ResourceManager.GetObject("treangle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва оновленого комітета:.
        /// </summary>
        public static string UpdatedCommiteeName {
            get {
                return ResourceManager.GetString("UpdatedCommiteeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Им&apos;я депутата, інформацію про якого було оновлено:.
        /// </summary>
        public static string UpdatedDeputy {
            get {
                return ResourceManager.GetString("UpdatedDeputy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Им&apos;я депутата, фото якого було оновлено:.
        /// </summary>
        public static string UpdatedDeputyPhoto {
            get {
                return ResourceManager.GetString("UpdatedDeputyPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва оновленого супровідного документа:.
        /// </summary>
        public static string UpdatedDocumentName {
            get {
                return ResourceManager.GetString("UpdatedDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва оновленої фракції:.
        /// </summary>
        public static string UpdatedFraction {
            get {
                return ResourceManager.GetString("UpdatedFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер оновленого законопроекту:.
        /// </summary>
        public static string UpdatedLawNumber {
            get {
                return ResourceManager.GetString("UpdatedLawNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тиждень оновленого засідання:.
        /// </summary>
        public static string UpdatedSessionPlan {
            get {
                return ResourceManager.GetString("UpdatedSessionPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap User_Groups_25px {
            get {
                object obj = ResourceManager.GetObject("User_Groups_25px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap User_Groups_white_100px {
            get {
                object obj = ResourceManager.GetObject("User_Groups_white_100px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap User_white_logo {
            get {
                object obj = ResourceManager.GetObject("User_white_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновлений rtf документ поіменного голосування:.
        /// </summary>
        public static string VotingRtfDoc {
            get {
                return ResourceManager.GetString("VotingRtfDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновлений xml документ поіменного голосування:.
        /// </summary>
        public static string VotingXmlDoc {
            get {
                return ResourceManager.GetString("VotingXmlDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість знайдених записів дорівнює 0.
        /// </summary>
        public static string ZeroCountWarning {
            get {
                return ResourceManager.GetString("ZeroCountWarning", resourceCulture);
            }
        }
    }
}
